version: '2'
services:
  gt-fhir2:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
#      - JDBC_URL=jdbc:postgresql://data.hdap.gatech.edu:5435/omop_v5
      - JDBC_URL=jdbc:postgresql://192.168.99.100:5438/postgres?currentSchema=omop_v5
      - JDBC_USERNAME=omop_v5
      - JDBC_PASSWORD=i3lworks
    ports:
      - "8080:8080"